apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mnemom-gateway.configmapName" . }}
  labels:
    {{- include "mnemom-gateway.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
