{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnemom-gateway.fullname" . }}
  labels:
    {{- include "mnemom-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.values }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
